### ISSUE TITLE
timestamp information from sdk is incorrect

### ISSUE THREAD

**Issue by ScorpioLidar** [cepton/sdk#1]
we got incorrect time value in test.
1.  void frameCallback(CeptonSensorHandle handle, int64_t start_timestamp,
                     size_t n_points, size_t stride, const uint8_t *points)
{
               CeptonSensor info;
		CeptonGetSensorInformation(handle, &info);
		if (info.serial_number > 0)
		{
                        //below powerup timestamp is wrong
			// info.power_up_timestamp;
}

2. timestamp for each point is incorrect
for (int i = 0; i < n_points; i++)
	{
		
		CeptonPoint const& pt =
			*reinterpret_cast<CeptonPoint const*>(points + i * stride);
		// Skip no-return points if keepInvalid was not set true
		if ((pt.flags & CEPTON_POINT_NO_RETURN) != 0) continue;

		CeptonSensorImagePoint point;
               //below timestamp is incorrect, maybe should plus powerup time, but powerup time in item1 is wrong
		// pt.relative_timestamp;

**Comment by liaody** [comment]
Please note that relative timestamp is from the point before. So the absolute time for each point is the header ts plus the *sum* of all the relative timestamps up to that point. If it is still unexpected, please provide some numbers to indicate what the reported value is and what the expected value is.

**Comment by ScorpioLidar** [comment]
Noted.
by adding a log in the callback function, i found that the powerup time is  incorrect and not fixed
expected timestamp should be close to system time: 
2023-07-05 14:48:14 ------------1688539694

       log piece from SW starting as below:
	行 1037: [2023-07-05 14:44:35.749] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:737267343360
	行 1038: [2023-07-05 14:44:35.845] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:737267343360
	行 1039: [2023-07-05 14:44:35.934] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:737267343360
	行 1040: [2023-07-05 14:44:36.025] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:737267343360
	行 1041: [2023-07-05 14:44:36.118] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:737267343360
	行 1042: [2023-07-05 14:44:36.210] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:737267343360
	行 1043: [2023-07-05 14:44:36.302] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:737267343360
	行 1047: [2023-07-05 14:44:36.396] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5603736668
	行 1048: [2023-07-05 14:44:36.487] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5603736668
	行 1049: [2023-07-05 14:44:36.594] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5603736668
	行 1050: [2023-07-05 14:44:36.677] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5603736668
	行 1054: [2023-07-05 14:44:36.763] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5603736668
	行 1055: [2023-07-05 14:44:36.857] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5604237137
	行 1056: [2023-07-05 14:44:36.948] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5604237137
	行 1057: [2023-07-05 14:44:46.448] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5604237137
	行 1061: [2023-07-05 14:44:46.538] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5604237137
	行 1062: [2023-07-05 14:44:46.630] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5604237137
	行 1063: [2023-07-05 14:44:46.722] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5604237137
	行 1064: [2023-07-05 14:44:46.815] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5604237137
	行 1068: [2023-07-05 14:44:46.906] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5614247215
	行 1069: [2023-07-05 14:44:46.999] [Rockfall] [I] [t=027388] DataSource: powerup time from sensorInfo:5614247215

**Comment by yzhang0231** [comment]
Hi @ScorpioLidar, `CeptonGetSensorInformation` returns an error code. When the error code is not equal to `CEPTON_SUCCESS`, the object `info` will not be touched by the sdk.
Could you change your code to below:
```C
CeptonSensor info;
int ec = CeptonGetSensorInformation(handle, &info);
if (ec == CEPTON_SUCCESS) {
  // use info.power_up_timestamp;
}
```

**Comment by ScorpioLidar** [comment]
hi, timestamp is still unexpected. in addition, the powerup time from sensor info changes if reset SW, while lidar keeps on

 480: [2023-07-06 09:25:23.981] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:384016711
	行 481: [2023-07-06 09:25:24.008] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:384016711
	行 482: [2023-07-06 09:25:24.101] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:384016711
	行 483: [2023-07-06 09:25:24.195] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:384016711
	行 484: [2023-07-06 09:25:24.287] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:384016711
	行 485: [2023-07-06 09:25:24.382] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388020522
	行 486: [2023-07-06 09:25:24.474] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388020522
	行 487: [2023-07-06 09:25:24.567] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388020522
	行 490: [2023-07-06 09:25:24.661] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388020522
	行 491: [2023-07-06 09:25:24.754] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388020522
	行 492: [2023-07-06 09:25:24.847] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388520994
	行 493: [2023-07-06 09:25:24.941] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388520994
	行 497: [2023-07-06 09:25:25.033] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388520994
	行 498: [2023-07-06 09:25:25.127] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388520994
	行 499: [2023-07-06 09:25:25.220] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388520994
	行 500: [2023-07-06 09:25:25.313] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:388520994
	行 503: [2023-07-06 09:25:25.406] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:389021801
	行 504: [2023-07-06 09:25:25.500] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:389021801
	行 505: [2023-07-06 09:25:25.593] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:389021801
	行 506: [2023-07-06 09:25:25.686] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:389021801
	行 509: [2023-07-06 09:25:25.779] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:389021801
	行 510: [2023-07-06 09:25:25.873] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:389522258
	行 511: [2023-07-06 09:25:25.965] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:389522258
	行 512: [2023-07-06 09:25:26.059] [Rockfall] [I] [t=019660] DataSource: powerup time from sensorInfo:389522258

**Comment by ScorpioLidar** [comment]
BTW，i just follow the "callback_task.cpp" sample code in SDK,  if you can't reproduce this issue there, could please provide your code to me, i can try it here.

**Comment by yzhang0231** [comment]
From your last log, I think the behavior matches with our expectation. The `power up time` is referenced with the LiDAR's power up time. I think your expectation of `expected timestamp should be close to system time` is not true for the `power_up_timestamp` field in the SensorInfo Object. 
To get your expectation, one needs to connect the sensor with PTP server, which syncs its time with your system. After that, the timestamp in the point cloud data would be in your system's time domain; the `power_up_timestamp` + `time_sync_offset` would be in your system's time domain. 

>
> could please provide your code to me, i can try it here.

I am using the same source file `callback_task.cpp`.

**Comment by ScorpioLidar** [comment]
sorry to replay late due to weekends. 
1. from test result here, even if keep lidar power-on, the "power up time" shall changes, not a fixed value. 
2. if a time sync is required, could please give me a guideline on debian ARM environment? as we use the time from cloud/SDK in product for vista P60 lidar, this should be an impaction after changing to X90

**Comment by yzhang0231** [comment]
>
> from test result here, even if keep lidar power-on, the "power up time" shall changes, not a fixed value.

Sorry for the confusion due to our variable naming. The description of the "PowerUpTime" here is: Microseconds since power up. These fields are exact copies from the sensor's information network packets. You should be able to find our packet definition in our [data format doc](https://developer.cepton.com/doc/data_format). We will put more comments in the SDK code in the future to avoid such misunderstanding. 

>
> if a time sync is required, could please give me a guideline on debian ARM environment? as we use the time from cloud/SDK in product for vista P60 lidar, this should be an impaction after changing to X90

Time sync over Ethernet requires a PTP server running in the system. One of the simplest setups is connect the Vista sensor to the debian ARM, and run [ptp4l](https://linux.die.net/man/8/ptp4l) on it with gPTP profile. Both P60 and X90 support PTP.
