### ISSUE TITLE
time sync for X90 on windows

### ISSUE THREAD

**Issue by ScorpioLidar** [cepton/sdk#2]
we have another product that uses Cepton P60 ,  and will change to X90 either.
but the data processing system of the product is running on X86 windows OS, and X90 lidar will connect to the windows machine  via ethernet directly. Then if the PTP time sync is required? and how to do this?
Your detailed guidance is really appreciated:-)

**Comment by liaody** [comment]
This is unrelated to the SDK. Use a hardware PTP server (e.g. Linux + ptp4l) on the network to solve this.
